### ISSUE TITLE
GarbageCollection.Cleaning.TestGarbageCollection() fails

### ISSUE THREAD

**Issue by abduelhamit** [MartinChavez/CSharp#3]
On my machine, `GetTotalCollections()` returns 4010±15.

My specs:
- Windows 8.1 64-bit
- Visual Studio 2013
- AMD Athlon II X4 630 (overclocked to 3.16 GHz)
- 4 GB RAM

**Comment by MartinChavez** [comment]
I tried the tests on all my machines, including my workstation (ram:16gb, processor:Intel i7 @ 3.60ghz), and it always ran out of memory (which is the point I am trying to make), what could possibly make your computer not run-out-of-memory?...very interesting, I really appreciate you took the time to raise an issue, I will investigate more (incresing the number to fix the test sounds like cheating...), thank you so much!

**Comment by MartinChavez** [comment]
It looks that this is no longer an issue, closing for now.
